import learningObjectives from "./Lo's.js";
import problemStatement from "./problemStatement.js";
import role from "./role.js";
import solution from "./solution.js";

const gradingPrompt = `
{
  "role": "${role}"
  "problem_statement": "${problemStatement}",
  "learning_objectives": "${learningObjectives}",
  "format": "
  Generate student evaluation results in the following format:
    results: [Evaluation Results]
    feedback: [Feedback]
    total_score: [Total Score]
    is_generated_by_ai: [Is Generated by AI?]
    generated_by_ai: [Generated by AI]
    generative_ai_used: [Generative AI Used?]
  "
}
`;

export default gradingPrompt;
